---
name: redis-debian

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis-debian
  azs: [z1, z2, z3]
  instances: 2
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  persistent_disk: 10240
  jobs:
  - name: login_banner
    release: os-conf
    properties:
      login_banner:
        text: |-

          Oooh welcome dear operator to Redis - installed by debian, monitored by monit,
          run inside a bpm container. Thanks BOSH!

          To tail all logs:
            tail -f /var/vcap/sys/log/{*.log,*/*.log}

          Redis Server logs:
            tail -f /var/vcap/sys/log/redis-debian/redis.log

          View monit status:
            monit summary

  - name: prepare_env
    release: os-conf
    properties:
      script: |-
        #!/bin/bash

        apt-get update
        apt-get install redis-server -y

        /usr/bin/redis-server -v
  - name: redis-debian
    release: redis-debian
    properties:
      password: ((redis-password))

variables:
- name: redis-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.2.0
- name: os-conf
  version: "19"
  url: git+https://github.com/cloudfoundry/os-conf-release
- name: redis-debian
  version: latest
