---
name: redis-debian

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis-debian
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: login_banner
    release: os-conf
    properties:
      login_banner:
        text: |-
          Oooh welcome dear operator to Redis - installed by debian, monitored by monit,
          run inside a bpm container. Thanks BOSH!
  - name: prepare_env
    release: os-conf
    properties:
      script: |-
        #!/bin/bash

        apt-get update
        apt-get install redis-server -y
  - name: redis-debian
    release: redis-debian
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.2.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: os-conf
  version: latest
  # url: git+https://github.com/cloudfoundry/os-conf-release
- name: redis-debian
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
