---
name: redis-debian

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: redis-debian
  azs: [z1, z2, z3]
  instances: 2
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  persistent_disk: 10240
  jobs:
  - name: login_banner
    release: os-conf
    properties:
      login_banner:
        text: |-

          Oooh welcome dear operator to Redis - installed by debian, monitored by monit,
          run inside a bpm container. Thanks BOSH!

          To tail all logs:
            tail -f /var/vcap/sys/log/{*.log,*/*.log}

          Redis Server logs:
            tail -f /var/vcap/sys/log/redis-debian/redis.log

          View monit status:
            monit summary

  - name: pre-start-script
    release: os-conf
    properties:
      script: |-
        #!/bin/bash

        chown root:root /tmp
        chmod 1777 /tmp
        apt-get update
        apt-get install redis-server -y

        /usr/bin/redis-server -v
  - name: redis-server
    release: redis-debian
    properties:
      password: ((redis-password))

variables:
- name: redis-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.12.3
- name: os-conf
  url: git+https://github.com/cloudfoundry/os-conf-release
  version: "20"
- name: redis-debian
  sha1: abe38ef93467135df50ad97a4aaa3585521406a0
  stemcell:
    os: ubuntu-trusty
    version: "97.22"
  url: https://s3.amazonaws.com/redis-debian-boshrelease/compiled-releases/redis-debian/redis-debian-2.0.0-ubuntu-xenial-97.22-20181008-022511-200921028-20181008022512.tgz
  version: 2.0.0
